/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/8.7/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    `cpp-library`
}

library {
    linkage = listOf(Linkage.SHARED)
    targetMachines = listOf(machines.linux.x86_64,
        machines.windows.x86, machines.windows.x86_64)
        source.from(file("src"))
    privateHeaders.from(file("src"))
    publicHeaders.from(file("include"))
}
