/*
 * This source file was generated by the Gradle 'init' task
 */
package psptools;

import javax.swing.UIManager;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

import psptools.ui.LaunchPage;

public class App {
    public static void main(String[] args) {
        System.out.println(String.join(", ", args));

        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        new LaunchPage().setVisible(true);
    }
}
